# --------------------------------------------
# 1️⃣ Build Stage
# --------------------------------------------
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Install dependencies first (for better caching)
COPY package*.json ./
RUN yarn install

# Copy project files
COPY . .

# Build Strapi project
RUN yarn build

# --------------------------------------------
# 2️⃣ Production Stage
# --------------------------------------------
FROM node:20-alpine AS runner

WORKDIR /app

# Copy only necessary files from builder
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
# COPY --from=builder /app/.tmp ./.tmp
# COPY --from=builder /app/public ./public
COPY --from=builder /app/config ./config
COPY --from=builder /app/src ./src

# Expose default Strapi port
EXPOSE 1337

# Set environment variables
ENV NODE_ENV=production

# Start the app
CMD ["yarn", "start"]
    